import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { mkdir, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { prisma } from "../src/lib/db";
import { revokeLinkDevice, authenticateLinkDevice } from "../src/lib/linkDevices";
import { purgeRevokedLinkDevices } from "../src/lib/linkDeviceRemoval";

async function main() {
  assert.match(process.env.DATABASE_URL ?? "", /^file:\/(?:private\/)?tmp\/homeplace-plants-[A-Za-z0-9]{6}\/test.db$/);
  const user = await prisma.user.create({ data: { name: "Removal test" } });
  const token = randomBytes(32).toString("base64url");
  const caps = JSON.stringify([{ name: "file.receive", version: 1, constraints: {} }]);
  const removed = await prisma.linkDevice.create({ data: { name: "Old device", userId: user.id, platform: "linux", platformVersion: "test", appVersion: "test", publicKey: "old", capabilities: caps, approvedCapabilities: caps, credentialHash: createHash("sha256").update(token).digest("hex") } });
  const kept = await prisma.linkDevice.create({ data: { name: "Current device", userId: user.id, platform: "macos", platformVersion: "test", appVersion: "test", publicKey: "current", capabilities: caps, approvedCapabilities: caps, credentialHash: "current-hash" } });
  const plant = await prisma.plant.create({ data: { userId: user.id, clientId: "keep-plant", name: "Keep plant", lastWateredAt: new Date(), intervalDays: 7 } });
  await prisma.linkPairing.create({ data: { deviceId: removed.id, name: removed.name, platform: "linux", platformVersion: "test", appVersion: "test", publicKey: removed.publicKey, capabilities: caps, claimSecretHash: "old-claim", expiresAt: new Date(Date.now() + 60000) } });
  await prisma.linkDeviceEvent.create({ data: { deviceId: removed.id, kind: "notification.deliver", payload: "{}" } });
  const keptEvent = await prisma.linkDeviceEvent.create({ data: { deviceId: kept.id, kind: "notification.deliver", payload: "{}" } });
  await prisma.linkCommand.create({ data: { userId: user.id, deviceId: removed.id, action: "system.lock", expiresAt: new Date(Date.now() + 60000) } });
  const upload = await prisma.linkUploadSession.create({ data: { sourceDeviceId: kept.id, targetDeviceId: removed.id, filename: "temp", mimeType: "text/plain", size: 1n, encryptedKey: "test", expiresAt: new Date(Date.now() + 60000) } });
  const directory = path.join(process.env.DATA_DIR!, "link-upload-sessions", upload.id);
  await mkdir(directory, { recursive: true });
  await writeFile(path.join(directory, "0"), "encrypted fixture");
  const storageName = randomBytes(24).toString("hex");
  const filePath = path.join(process.env.DATA_DIR!, "link-transfers", storageName);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, "encrypted transfer fixture");
  const transfer = await prisma.linkFileTransfer.create({ data: { sourceDeviceId: removed.id, targetDeviceId: kept.id, filename: "temp", mimeType: "text/plain", size: 1n, sha256: "0".repeat(64), storageName, encryptedKey: "test", expiresAt: new Date(Date.now() + 60000) } });
  const offer = await prisma.linkDeviceEvent.create({ data: { deviceId: kept.id, kind: "share.offer", payload: JSON.stringify({ transferId: transfer.id }) } });
  const batch = await prisma.linkShareBatch.create({ data: { sourceDeviceId: removed.id, targetDeviceId: kept.id, expiresAt: new Date(Date.now() + 60000), files: { create: [{ ordinal: 0, filename: "temp", mimeType: "text/plain", size: 1n, sha256: "0".repeat(64) }] } } });
  const credential = new Request("http://localhost", { headers: { Authorization: `Bearer ${token}` } });
  assert.ok(await authenticateLinkDevice(credential));
  assert.equal(await revokeLinkDevice(removed.id), true);
  assert.equal(await authenticateLinkDevice(credential), null);
  assert.equal(await prisma.linkDevice.findUnique({ where: { id: removed.id } }), null);
  assert.equal(await prisma.linkPairing.count({ where: { deviceId: removed.id } }), 0);
  assert.equal(await prisma.linkPairing.count({ where: { claimSecretHash: "old-claim" } }), 0);
  assert.equal(await prisma.linkCommand.count({ where: { deviceId: removed.id } }), 0);
  assert.equal(await prisma.linkUploadSession.count({ where: { id: upload.id } }), 0);
  await assert.rejects(access(directory));
  await assert.rejects(access(filePath));
  assert.equal(await prisma.linkFileTransfer.findUnique({ where: { id: transfer.id } }), null);
  assert.equal(await prisma.linkDeviceEvent.findUnique({ where: { id: offer.id } }), null);
  assert.equal(await prisma.linkShareBatch.findUnique({ where: { id: batch.id } }), null);
  assert.equal(await prisma.linkBatchFile.count({ where: { batchId: batch.id } }), 0);
  assert.equal(await prisma.setting.count({ where: { key: { startsWith: "link.device-file-cleanup." } } }), 0);
  assert.ok(await prisma.linkDevice.findUnique({ where: { id: kept.id } }));
  assert.equal(await purgeRevokedLinkDevices([kept.id]), 0);
  assert.ok(await prisma.plant.findUnique({ where: { id: plant.id } }));
  assert.ok(await prisma.linkDeviceEvent.findUnique({ where: { id: keptEvent.id } }));
  assert.equal(await revokeLinkDevice(removed.id), false);
  console.log("PASS: removed credentials/metadata/chunks gone; other devices and personal data preserved.");
}
main().finally(() => prisma.$disconnect());
